---
title: "Generating Baseline Model Inputs"
author: "Emanuel Rodriguez"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Who Should Read This

The `cvpiaData` package comes bundled with a set of baseline model inputs, that 
should satisfy the need for most users of the package. This guide is intended
for users wishing to create custom baseline inputs to the SIT model. 


# Building Instream Rearing Habitat

```{r}
# set a watershed

get_flow <- function(watersheds, years=c(1980, 1999)) {
  
    # get the flow values at the dates
    dplyr::pull(dplyr::filter(dplyr::select(cvpiaFlow::flows_cfs, date, watersheds), 
                                             lubridate::year(date) >= years[1], 
                                             lubridate::year(date) <= years[2]), 2)
    
  
}

antelope_creek_flows <- get_flow("Antelope Creek")

antelope_fr_fry_instream <- purrr::map_dbl(antelope_creek_flows, function(flow) {
  cvpiaHabitat::set_instream_habitat(watershed = "Antelope Creek", species = "fr", life_stage = "fry", 
                                   flow = antelope_creek_flows)
})


battle_creek_flows <- get_flow("Battle Creek")

battle_creek_fr_fry_instream <- cvpiaHabitat::set_spawning_habitat(watershed = "Battle Creek", 
                                                                   species = "fr", 
                                                                   flow = battle_creek_flows)


bear_creek_flows <- get_flow("Bear Creek")

bear_creek_fr_fry_instream <- cvpiaHabitat::set_spawning_habitat(watershed = "Bear Creek", 
                                                                   species = "fr", 
                                                                   flow = bear_creek_flows)

```
